# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pharmacy_pb2 as pharmacy__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pharmacy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddMedicine = channel.unary_unary(
                '/pharmacy.ReferenceService/AddMedicine',
                request_serializer=pharmacy__pb2.AddMedicineRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.OperationResult.FromString,
                _registered_method=True)
        self.ListMedicines = channel.unary_unary(
                '/pharmacy.ReferenceService/ListMedicines',
                request_serializer=pharmacy__pb2.Empty.SerializeToString,
                response_deserializer=pharmacy__pb2.MedicineList.FromString,
                _registered_method=True)
        self.SearchMedicines = channel.unary_unary(
                '/pharmacy.ReferenceService/SearchMedicines',
                request_serializer=pharmacy__pb2.SearchRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.MedicineList.FromString,
                _registered_method=True)
        self.ValidateSale = channel.unary_unary(
                '/pharmacy.ReferenceService/ValidateSale',
                request_serializer=pharmacy__pb2.ValidateSaleRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.ValidateSaleResponse.FromString,
                _registered_method=True)
        self.DecreaseMedicineQuantity = channel.unary_unary(
                '/pharmacy.ReferenceService/DecreaseMedicineQuantity',
                request_serializer=pharmacy__pb2.UpdateQuantityRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.OperationResult.FromString,
                _registered_method=True)
        self.CheckExpiration = channel.unary_unary(
                '/pharmacy.ReferenceService/CheckExpiration',
                request_serializer=pharmacy__pb2.ExpirationRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.ExpirationStatus.FromString,
                _registered_method=True)
        self.RemoveExpired = channel.unary_unary(
                '/pharmacy.ReferenceService/RemoveExpired',
                request_serializer=pharmacy__pb2.Empty.SerializeToString,
                response_deserializer=pharmacy__pb2.MedicineList.FromString,
                _registered_method=True)


class ReferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddMedicine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMedicines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMedicines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecreaseMedicineQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExpiration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveExpired(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddMedicine': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMedicine,
                    request_deserializer=pharmacy__pb2.AddMedicineRequest.FromString,
                    response_serializer=pharmacy__pb2.OperationResult.SerializeToString,
            ),
            'ListMedicines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMedicines,
                    request_deserializer=pharmacy__pb2.Empty.FromString,
                    response_serializer=pharmacy__pb2.MedicineList.SerializeToString,
            ),
            'SearchMedicines': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMedicines,
                    request_deserializer=pharmacy__pb2.SearchRequest.FromString,
                    response_serializer=pharmacy__pb2.MedicineList.SerializeToString,
            ),
            'ValidateSale': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSale,
                    request_deserializer=pharmacy__pb2.ValidateSaleRequest.FromString,
                    response_serializer=pharmacy__pb2.ValidateSaleResponse.SerializeToString,
            ),
            'DecreaseMedicineQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.DecreaseMedicineQuantity,
                    request_deserializer=pharmacy__pb2.UpdateQuantityRequest.FromString,
                    response_serializer=pharmacy__pb2.OperationResult.SerializeToString,
            ),
            'CheckExpiration': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExpiration,
                    request_deserializer=pharmacy__pb2.ExpirationRequest.FromString,
                    response_serializer=pharmacy__pb2.ExpirationStatus.SerializeToString,
            ),
            'RemoveExpired': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveExpired,
                    request_deserializer=pharmacy__pb2.Empty.FromString,
                    response_serializer=pharmacy__pb2.MedicineList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pharmacy.ReferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pharmacy.ReferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddMedicine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.ReferenceService/AddMedicine',
            pharmacy__pb2.AddMedicineRequest.SerializeToString,
            pharmacy__pb2.OperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMedicines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.ReferenceService/ListMedicines',
            pharmacy__pb2.Empty.SerializeToString,
            pharmacy__pb2.MedicineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMedicines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.ReferenceService/SearchMedicines',
            pharmacy__pb2.SearchRequest.SerializeToString,
            pharmacy__pb2.MedicineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.ReferenceService/ValidateSale',
            pharmacy__pb2.ValidateSaleRequest.SerializeToString,
            pharmacy__pb2.ValidateSaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecreaseMedicineQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.ReferenceService/DecreaseMedicineQuantity',
            pharmacy__pb2.UpdateQuantityRequest.SerializeToString,
            pharmacy__pb2.OperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckExpiration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.ReferenceService/CheckExpiration',
            pharmacy__pb2.ExpirationRequest.SerializeToString,
            pharmacy__pb2.ExpirationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveExpired(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.ReferenceService/RemoveExpired',
            pharmacy__pb2.Empty.SerializeToString,
            pharmacy__pb2.MedicineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddMedicine = channel.unary_unary(
                '/pharmacy.CoreService/AddMedicine',
                request_serializer=pharmacy__pb2.AddMedicineRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.OperationResult.FromString,
                _registered_method=True)
        self.ListMedicines = channel.unary_unary(
                '/pharmacy.CoreService/ListMedicines',
                request_serializer=pharmacy__pb2.Empty.SerializeToString,
                response_deserializer=pharmacy__pb2.MedicineList.FromString,
                _registered_method=True)
        self.SearchMedicines = channel.unary_unary(
                '/pharmacy.CoreService/SearchMedicines',
                request_serializer=pharmacy__pb2.SearchRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.MedicineList.FromString,
                _registered_method=True)
        self.CheckExpiration = channel.unary_unary(
                '/pharmacy.CoreService/CheckExpiration',
                request_serializer=pharmacy__pb2.ExpirationRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.ExpirationStatus.FromString,
                _registered_method=True)
        self.RemoveExpired = channel.unary_unary(
                '/pharmacy.CoreService/RemoveExpired',
                request_serializer=pharmacy__pb2.Empty.SerializeToString,
                response_deserializer=pharmacy__pb2.MedicineList.FromString,
                _registered_method=True)
        self.SellMedicine = channel.unary_unary(
                '/pharmacy.CoreService/SellMedicine',
                request_serializer=pharmacy__pb2.SellMedicineRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.SellMedicineResponse.FromString,
                _registered_method=True)
        self.ListSales = channel.unary_unary(
                '/pharmacy.CoreService/ListSales',
                request_serializer=pharmacy__pb2.Empty.SerializeToString,
                response_deserializer=pharmacy__pb2.SaleList.FromString,
                _registered_method=True)
        self.CalculateFridayDiscount = channel.unary_unary(
                '/pharmacy.CoreService/CalculateFridayDiscount',
                request_serializer=pharmacy__pb2.DiscountRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DiscountResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddMedicine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMedicines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMedicines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExpiration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveExpired(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellMedicine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSales(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateFridayDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddMedicine': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMedicine,
                    request_deserializer=pharmacy__pb2.AddMedicineRequest.FromString,
                    response_serializer=pharmacy__pb2.OperationResult.SerializeToString,
            ),
            'ListMedicines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMedicines,
                    request_deserializer=pharmacy__pb2.Empty.FromString,
                    response_serializer=pharmacy__pb2.MedicineList.SerializeToString,
            ),
            'SearchMedicines': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMedicines,
                    request_deserializer=pharmacy__pb2.SearchRequest.FromString,
                    response_serializer=pharmacy__pb2.MedicineList.SerializeToString,
            ),
            'CheckExpiration': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExpiration,
                    request_deserializer=pharmacy__pb2.ExpirationRequest.FromString,
                    response_serializer=pharmacy__pb2.ExpirationStatus.SerializeToString,
            ),
            'RemoveExpired': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveExpired,
                    request_deserializer=pharmacy__pb2.Empty.FromString,
                    response_serializer=pharmacy__pb2.MedicineList.SerializeToString,
            ),
            'SellMedicine': grpc.unary_unary_rpc_method_handler(
                    servicer.SellMedicine,
                    request_deserializer=pharmacy__pb2.SellMedicineRequest.FromString,
                    response_serializer=pharmacy__pb2.SellMedicineResponse.SerializeToString,
            ),
            'ListSales': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSales,
                    request_deserializer=pharmacy__pb2.Empty.FromString,
                    response_serializer=pharmacy__pb2.SaleList.SerializeToString,
            ),
            'CalculateFridayDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateFridayDiscount,
                    request_deserializer=pharmacy__pb2.DiscountRequest.FromString,
                    response_serializer=pharmacy__pb2.DiscountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pharmacy.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pharmacy.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddMedicine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/AddMedicine',
            pharmacy__pb2.AddMedicineRequest.SerializeToString,
            pharmacy__pb2.OperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMedicines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/ListMedicines',
            pharmacy__pb2.Empty.SerializeToString,
            pharmacy__pb2.MedicineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMedicines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/SearchMedicines',
            pharmacy__pb2.SearchRequest.SerializeToString,
            pharmacy__pb2.MedicineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckExpiration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/CheckExpiration',
            pharmacy__pb2.ExpirationRequest.SerializeToString,
            pharmacy__pb2.ExpirationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveExpired(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/RemoveExpired',
            pharmacy__pb2.Empty.SerializeToString,
            pharmacy__pb2.MedicineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellMedicine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/SellMedicine',
            pharmacy__pb2.SellMedicineRequest.SerializeToString,
            pharmacy__pb2.SellMedicineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/ListSales',
            pharmacy__pb2.Empty.SerializeToString,
            pharmacy__pb2.SaleList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateFridayDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pharmacy.CoreService/CalculateFridayDiscount',
            pharmacy__pb2.DiscountRequest.SerializeToString,
            pharmacy__pb2.DiscountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
